"""
================================================================================
LilyPond to MEI 5.1 Converter (Accademia degli Incompresi Partbooks)
================================================================================
Author: Generated by Gemini Notebook for Orpheus Instituut
Date: 2026-09-01

This script parses LilyPond-style musical content and exports it into highly 
FAIR-compatible, syntactically valid MEI 5.1 XML in mensural notation style.

================================================================================

Examples command:

--ver = version : {"d": "diplomatic", "p": "performance"}

```bash
python3 ly2mei.py --batch --dir ./data --ver d

```


"""

import os
import re
import uuid
import argparse
from pathlib import Path
from lxml import etree


class LilyPondToMEIConverter:
    def __init__(self, relative_start="c'"):
        self.relative_start = relative_start
        self.diatonic_map = {"c": 0, "d": 1, "e": 2, "f": 3, "g": 4, "a": 5, "b": 6}
        self.inverse_diatonic = {v: k for k, v in self.diatonic_map.items()}

        # Clef mappings
        self.clef_map = {
            "petrucci-c1": {"shape": "C", "line": "1"},
            "petrucci-c2": {"shape": "C", "line": "2"},
            "petrucci-c3": {"shape": "C", "line": "3"},
            "petrucci-c4": {"shape": "C", "line": "4"},
            "petrucci-f4": {"shape": "F", "line": "4"},
            "mensural-c1": {"shape": "C", "line": "1"},
            "mensural-c2": {"shape": "C", "line": "2"},
            "mensural-c3": {"shape": "C", "line": "3"},
            "mensural-c4": {"shape": "C", "line": "4"},
            "mensural-f4": {"shape": "F", "line": "4"},
            "treble": {"shape": "G", "line": "2"},
            "treble_8": {"shape": "G", "line": "2", "dis": "8", "dis.place": "below"},
            "bass": {"shape": "F", "line": "4"},
        }

        # Key signature mappings (standard MEI 5.1 representation)
        self.key_sig_map = {
            ("c", "major"): "0",
            ("a", "minor"): "0",
            ("f", "major"): "1f",
            ("d", "minor"): "1f",
            ("bes", "major"): "2f",
            ("g", "minor"): "2f",
            ("ees", "major"): "3f",
            ("c", "minor"): "3f",
            ("aes", "major"): "4f",
            ("f", "minor"): "4f",
            ("des", "major"): "5f",
            ("bes", "minor"): "5f",
            ("ges", "major"): "6f",
            ("ees", "minor"): "6f",
            ("ces", "major"): "7f",
            ("aes", "minor"): "7f",
            ("g", "major"): "1s",
            ("e", "minor"): "1s",
            ("d", "major"): "2s",
            ("b", "minor"): "2s",
            ("a", "major"): "3s",
            ("fis", "minor"): "3s",
            ("e", "major"): "4s",
            ("cis", "minor"): "4s",
            ("b", "major"): "5s",
            ("gis", "minor"): "5s",
            ("fis", "major"): "6s",
            ("dis", "minor"): "6s",
            ("cis", "major"): "7s",
            ("ais", "minor"): "7s",
        }

        # Key signature accidentals for suppression logic
        self.key_sig_accidentals = {
            "0": {},
            "1f": {"b": "f"},
            "2f": {"b": "f", "e": "f"},
            "3f": {"b": "f", "e": "f", "a": "f"},
            "4f": {"b": "f", "e": "f", "a": "f", "d": "f"},
            "5f": {"b": "f", "e": "f", "a": "f", "d": "f", "g": "f"},
            "6f": {"b": "f", "e": "f", "a": "f", "d": "f", "g": "f", "c": "f"},
            "7f": {
                "b": "f",
                "e": "f",
                "a": "f",
                "d": "f",
                "g": "f",
                "c": "f",
                "f": "f",
            },
            "1s": {"f": "s"},
            "2s": {"f": "s", "c": "s"},
            "3s": {"f": "s", "c": "s", "g": "s"},
            "4s": {"f": "s", "c": "s", "g": "s", "d": "s"},
            "5s": {"f": "s", "c": "s", "g": "s", "d": "s", "a": "s"},
            "6s": {"f": "s", "c": "s", "g": "s", "d": "s", "a": "s", "e": "s"},
            "7s": {
                "f": "s",
                "c": "s",
                "g": "s",
                "d": "s",
                "a": "s",
                "e": "s",
                "b": "s",
            },
        }

        # Time to mensur mapping
        self.time_map = {
            "2/2": {"sign": "C", "tempus": "2", "slash": "1"},
            "4/4": {"sign": "C", "tempus": "2"},
            "3/2": {"sign": "O", "tempus": "3", "slash": "1"},
            "3/4": {"sign": "O", "tempus": "3"},
        }

        # Mensural duration names mapping for Verovio
        self.dur_map = {
            "longa": "longa",
            "breve": "brevis",
            "1": "semibrevis",
            "2": "minima",
            "4": "semiminima",
            "8": "fusa",
            "16": "semifusa",
            "32": "semifusa",
        }

    def get_short_id(self):
        return f"w{uuid.uuid4().hex[:7]}"

    def preprocess_notes(self, text_content):
        # Remove comments first
        lines = []
        for line in text_content.splitlines():
            line_no_comment = line.split("%", 1)[0]
            lines.append(line_no_comment)
        content = "\n".join(lines)

        # Ensure space around curly braces { }
        content = re.sub(r"(?<!\s)\{", " {", content)
        content = re.sub(r"\}(?!\s)", "} ", content)

        # Ensure space before backslash commands if they stick to note/rest/octave tokens
        # BUT ignore \breve and \longa to allow f\breve and f\longa to stay together
        content = re.sub(
            r"(?<=[a-zA-Z0-9',!\]\)])\\(?!(breve|longa)\b)", r" \\", content
        )

        return content

    def parse_note_or_rest(self, token):
        # Match step, accidental, octave, force accidental (!), duration (numeric or string), dots
        pattern = r"^([a-grs])(is|es|isis|eses|s|f|ss|ff)?([',]*)?([!]*)(\\breve|\\longa|\d+)?(\.*)$"
        match = re.match(pattern, token)
        if not match:
            return None
        name, accid, octave_mod, force, dur, dots = match.groups()

        octave_mod = octave_mod or ""
        oct_shift = octave_mod.count("'") - octave_mod.count(",")
        num_dots = len(dots) if dots else 0
        has_force = bool(force)

        if dur:
            dur = dur.lstrip("\\")

        mei_accid = None
        if accid in ["is", "s"]:
            mei_accid = "s"
        elif accid in ["es", "f"]:
            mei_accid = "f"
        elif accid in ["isis", "ss"]:
            mei_accid = "ss"
        elif accid in ["eses", "ff"]:
            mei_accid = "ff"

        return {
            "name": name,
            "accid": mei_accid,
            "force_accid": has_force,
            "oct_shift": oct_shift,
            "dur": dur,
            "dots": num_dots,
        }

    def extract_spans_and_clean(self, token):
        start_ligature = False
        end_ligature = False
        start_beam = False
        end_beam = False
        start_slur = False
        end_slur = False

        clean = token

        if clean.startswith(r"\[") or clean.startswith(r"\\["):
            start_ligature = True
            clean = clean[2:]
        elif clean.startswith("["):
            if clean == "[":
                return {"type": "beam_start"}
            start_beam = True
            clean = clean[1:]

        if clean == r"\]" or clean == r"\\\]":
            return {"type": "ligature_end"}

        while True:
            if clean.endswith(r"\]") or clean.endswith(r"\\\]"):
                end_ligature = True
                clean = clean[:-2]
            elif clean.endswith("]"):
                end_beam = True
                clean = clean[:-1]
            elif clean.endswith(")"):
                end_slur = True
                clean = clean[:-1]
            elif clean.endswith("("):
                start_slur = True
                clean = clean[:-1]
            else:
                break

        return {
            "type": "note_token",
            "clean": clean,
            "start_ligature": start_ligature,
            "end_ligature": end_ligature,
            "start_beam": start_beam,
            "end_beam": end_beam,
            "start_slur": start_slur,
            "end_slur": end_slur,
        }

    def resolve_relative_octaves(self, raw_tokens_or_string):
        if isinstance(raw_tokens_or_string, str):
            notes_str = raw_tokens_or_string
        else:
            notes_str = " ".join(raw_tokens_or_string)

        notes_str = self.preprocess_notes(notes_str)
        raw_tokens = notes_str.split()

        # Preprocess relative environment and parse initial relative starting pitch
        relative_match = re.search(
            r"\\relative\s+([a-grs])(is|es|isis|eses|s|f|ss|ff)?([',]*)", notes_str
        )
        if relative_match:
            rel_note = relative_match.group(1)
            rel_accid = relative_match.group(2) or ""
            rel_oct = relative_match.group(3) or ""
            self.relative_start = f"{rel_note}{rel_accid}{rel_oct}"
            # Strip out relative structures and braces from raw_tokens
            raw_tokens = [t for t in raw_tokens if t not in ["\\relative", "{", "}"]]
            # Remove the first octave start argument from the tokens list
            if raw_tokens and re.match(
                r"^([a-g][is|es|isis|eses|s|f|ss|ff]*[',]*)$", raw_tokens[0]
            ):
                raw_tokens.pop(0)

        start_info = self.parse_note_or_rest(self.relative_start)
        start_step = self.diatonic_map[start_info["name"]]
        start_octave = 3 + start_info["oct_shift"]
        prev_diatonic = start_octave * 7 + start_step

        resolved_elements = []
        active_dur = "4"
        active_dots = 0

        ficta = False
        coloration = False
        stem_dir = None

        i = 0
        while i < len(raw_tokens):
            tok = raw_tokens[i]

            if tok == "\\ficta":
                ficta = True
                i += 1
                continue
            elif tok == "\\turnBlack":
                coloration = True
                i += 1
                continue
            elif tok in ["\\turnWhite", "\\normalColor"]:
                coloration = False
                i += 1
                continue
            elif tok == "\\stemUp":
                stem_dir = "up"
                i += 1
                continue
            elif tok == "\\stemDown":
                stem_dir = "down"
                i += 1
                continue
            elif tok == "\\stemNeutral":
                stem_dir = None
                i += 1
                continue

            if tok == "\\clef":
                resolved_elements.append(
                    {"type": "clef", "val": raw_tokens[i + 1].strip('"')}
                )
                i += 2
                continue
            elif tok == "\\key":
                mode_val = "major"
                if i + 2 < len(raw_tokens) and raw_tokens[i + 2] in [
                    "\\major",
                    "\\minor",
                ]:
                    mode_val = raw_tokens[i + 2].strip("\\")
                resolved_elements.append(
                    {"type": "keySig", "pitch": raw_tokens[i + 1], "mode": mode_val}
                )
                i += 3
                continue
            elif tok == "\\time":
                resolved_elements.append({"type": "mensur", "time": raw_tokens[i + 1]})
                i += 2
                continue
            elif tok == "\\break":
                resolved_elements.append({"type": "break"})
                i += 1
                continue
            elif tok == "\\bar":
                resolved_elements.append(
                    {"type": "barLine", "form": raw_tokens[i + 1].strip('"')}
                )
                i += 2
                continue

            span_res = self.extract_spans_and_clean(tok)
            if span_res["type"] == "beam_start":
                resolved_elements.append({"type": "beam_start"})
                i += 1
                continue
            elif span_res["type"] == "beam_end":
                resolved_elements.append({"type": "beam_end"})
                i += 1
                continue
            elif span_res["type"] == "ligature_end":
                resolved_elements.append({"type": "ligature_end"})
                i += 1
                continue

            clean_tok = span_res["clean"]
            if span_res["start_ligature"]:
                resolved_elements.append({"type": "ligature_start"})

            if not clean_tok:
                i += 1
                continue

            info = self.parse_note_or_rest(clean_tok)
            if not info:
                resolved_elements.append({"type": "unparsed", "value": clean_tok})
                i += 1
                continue

            if info["dur"] is not None:
                active_dur = info["dur"]
                active_dots = info["dots"]

            if info["name"] in ["r", "s"]:
                resolved_elements.append(
                    {
                        "type": "rest" if info["name"] == "r" else "space",
                        "dur": active_dur,
                        "dots": active_dots,
                    }
                )
            else:
                step_char = info["name"]
                step_val = self.diatonic_map[step_char]

                best_diatonic = None
                min_diff = 999
                prev_octave = prev_diatonic // 7

                for test_octave in [prev_octave - 1, prev_octave, prev_octave + 1]:
                    test_diatonic = test_octave * 7 + step_val
                    diff = test_diatonic - prev_diatonic
                    if abs(diff) < min_diff:
                        min_diff = abs(diff)
                        best_diatonic = test_diatonic

                final_diatonic = best_diatonic + (info["oct_shift"] * 7)
                final_octave = final_diatonic // 7

                resolved_elements.append(
                    {
                        "type": "note",
                        "pname": step_char,
                        "oct": final_octave,
                        "accid": info["accid"],
                        "force_accid": info["force_accid"],
                        "dur": active_dur,
                        "dots": active_dots,
                        "coloration": coloration,
                        "ficta": ficta,
                        "stem_dir": stem_dir,
                        "start_ligature": span_res["start_ligature"],
                        "end_ligature": span_res["end_ligature"],
                        "start_slur": span_res["start_slur"],
                        "end_slur": span_res["end_slur"],
                        "start_beam": span_res["start_beam"],
                        "end_beam": span_res["end_beam"],
                    }
                )

                ficta = False
                prev_diatonic = final_diatonic

            if span_res["end_ligature"]:
                resolved_elements.append({"type": "ligature_end"})

            i += 1

        return resolved_elements

    def parse_lyrics(self, lyrics_text):
        # Clean lyrics content to strip out lyricmode markers and outer braces
        lyrics_text = lyrics_text.strip()
        lyrics_text = re.sub(
            r"^\\lyric_?mode\s*\{", "", lyrics_text, flags=re.IGNORECASE
        )
        lyrics_text = lyrics_text.strip()
        if lyrics_text.endswith("}"):
            lyrics_text = lyrics_text[:-1].strip()
        lyrics_text = lyrics_text.replace("{", "").replace("}", "")

        # Process skip indicators
        lyrics_text = re.sub(r"\\skip\s*(\d+)", r"\\skip\1", lyrics_text)
        tokens = lyrics_text.split()
        processed = []

        for i, tok in enumerate(tokens):
            if tok in ["--", "_"]:
                continue

            if tok.startswith("\\skip"):
                processed.append({"type": "skip"})
                continue

            preceded_by_dash = i > 0 and tokens[i - 1] == "--"
            followed_by_dash = i < len(tokens) - 1 and tokens[i + 1] == "--"

            wordpos = "single"
            con = None

            if preceded_by_dash and followed_by_dash:
                wordpos = "i"
                con = "d"
            elif preceded_by_dash:
                wordpos = "t"
            elif followed_by_dash:
                wordpos = "s"
                con = "d"

            processed.append(
                {"type": "syllable", "text": tok, "wordpos": wordpos, "con": con}
            )
        return processed

    def generate_mei(
        self, resolved_music, parsed_lyrics, title_text="LilyPond Export", metadata=None
    ):
        namespaces = {None: "http://www.music-encoding.org/ns/mei"}
        root = etree.Element("mei", meiversion="5.1", nsmap=namespaces)

        metadata = metadata or {}

        # Metadata Header
        mei_head = etree.SubElement(root, "meiHead")
        mei_head.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        file_desc = etree.SubElement(mei_head, "fileDesc")
        file_desc.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        title_stmt = etree.SubElement(file_desc, "titleStmt")
        title_stmt.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        title_el = etree.SubElement(title_stmt, "title")
        title_el.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        title_el.text = title_text

        madrigal_book = metadata.get("madrigal_book")
        if madrigal_book:
            sub_title = etree.SubElement(title_stmt, "title", type="subordinate")
            sub_title.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            sub_title.text = madrigal_book

        resp_stmt = etree.SubElement(title_stmt, "respStmt")
        resp_stmt.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        composer = metadata.get("composer")
        if composer:
            comp_el = etree.SubElement(resp_stmt, "persName", role="composer")
            comp_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            comp_el.text = composer

        poet = metadata.get("poet")
        if poet:
            poet_el = etree.SubElement(resp_stmt, "persName", role="lyricist")
            poet_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            poet_el.text = poet

        publisher = metadata.get("publisher")
        if publisher:
            pub_el = etree.SubElement(resp_stmt, "persName", role="arranger")
            pub_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            pub_el.text = publisher

        pub_stmt = etree.SubElement(file_desc, "pubStmt")
        pub_stmt.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        if publisher:
            publisher_el = etree.SubElement(pub_stmt, "publisher")
            publisher_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            publisher_el.text = publisher
        year = metadata.get("year")
        if year:
            date_el = etree.SubElement(pub_stmt, "date")
            date_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            date_el.text = year

        collection = metadata.get("collection")
        if collection:
            series_stmt = etree.SubElement(file_desc, "seriesStmt")
            series_stmt.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            coll_title = etree.SubElement(series_stmt, "title")
            coll_title.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            coll_title.text = collection

        annotator = metadata.get("annotator", "")
        if annotator:
            notes_stmt = etree.SubElement(file_desc, "notesStmt")
            notes_stmt.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            annot_el = etree.SubElement(notes_stmt, "annot")
            annot_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            annot_el.text = annotator

        initial_clef = None
        initial_keysig = None

        for item in resolved_music:
            if item["type"] == "clef" and not initial_clef:
                initial_clef = item["val"]
            elif item["type"] == "keySig" and not initial_keysig:
                initial_keysig = self.key_sig_map.get(
                    (item["pitch"], item["mode"]), "0"
                )

        if not initial_clef:
            raise ValueError(
                "No clef is stated at the beginning of the LilyPond music stream."
            )

        # Staff definitions - use "mensural.white" notationtype
        score_def = etree.Element("scoreDef")
        score_def.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        score_def.set("mnum.visible", "false")
        staff_grp = etree.SubElement(score_def, "staffGrp")
        staff_grp.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        staff_def = etree.SubElement(
            staff_grp, "staffDef", n="1", lines="5", notationtype="mensural.white"
        )
        staff_def.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        voice_label = metadata.get("vocal_label")
        if voice_label:
            staff_def.set("label", voice_label)

        # Large decorative initial letter (Incipit) inside <staffDef>
        incipit = metadata.get("incipit")
        if incipit:
            label_el = etree.SubElement(staff_def, "label")
            label_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            rend_el = etree.SubElement(
                label_el,
                "rend",
                fontsize="48pt",
                fontweight="bold",
                valign="middle",
                halign="left",
                translate="-15",
            )
            rend_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )
            rend_el.text = incipit

        clef_info = self.clef_map.get(initial_clef, {"shape": "G", "line": "2"})
        clef_el_def = etree.SubElement(
            staff_def, "clef", shape=clef_info["shape"], line=clef_info["line"]
        )
        clef_el_def.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        if "dis" in clef_info:
            clef_el_def.set("dis", clef_info["dis"])
            clef_el_def.set("dis.place", clef_info["dis.place"])

        active_key_sig = initial_keysig or "0"
        key_sig_el_def = etree.SubElement(staff_def, "keySig", sig=active_key_sig)
        key_sig_el_def.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        # Music Elements
        music_el = etree.SubElement(root, "music")
        music_el.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        body = etree.SubElement(music_el, "body")
        body.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        mdiv = etree.SubElement(body, "mdiv")
        mdiv.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        score = etree.SubElement(mdiv, "score")
        score.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        score.append(score_def)

        section = etree.SubElement(score, "section")
        section.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        # We wrap lines in <measure> elements with invisible barlines to preserve formatting
        measure_count = 1
        current_measure = etree.SubElement(
            section, "measure", n=str(measure_count), right="invis"
        )
        current_measure.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        staff = etree.SubElement(current_measure, "staff", n="1")
        staff.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )
        layer = etree.SubElement(staff, "layer", n="1")
        layer.set(
            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
            self.get_short_id(),
        )

        container_stack = [layer]
        slur_start_id = None
        active_slurs = []
        lyric_idx = 0

        active_beam = False
        is_first_note_of_beam = False

        # Skip initial clef/keysig rendering in layer to avoid redundancy in Verovio
        clef_skipped = False
        keysig_skipped = False

        for idx, item in enumerate(resolved_music):
            if item["type"] == "clef":
                if not clef_skipped:
                    clef_skipped = True
                    continue
                c_info = self.clef_map.get(item["val"], {"shape": "G", "line": "2"})
                clef_el = etree.SubElement(
                    container_stack[-1],
                    "clef",
                    shape=c_info["shape"],
                    line=c_info["line"],
                )
                clef_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                if "dis" in c_info:
                    clef_el.set("dis", c_info["dis"])
                    clef_el.set("dis.place", c_info["dis.place"])
                continue

            elif item["type"] == "keySig":
                sig_val = self.key_sig_map.get((item["pitch"], item["mode"]), "0")
                active_key_sig = sig_val
                if not keysig_skipped:
                    keysig_skipped = True
                    continue
                key_sig_el = etree.SubElement(
                    container_stack[-1], "keySig", sig=sig_val
                )
                key_sig_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                continue

            elif item["type"] == "mensur":
                m_info = self.time_map.get(
                    item["time"], {"sign": "C", "tempus": "2", "slash": "1"}
                )
                m_el = etree.SubElement(
                    container_stack[-1], "mensur", sign=m_info["sign"]
                )
                m_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                if "tempus" in m_info:
                    m_el.set("tempus", m_info["tempus"])
                if "slash" in m_info:
                    m_el.set("slash", m_info["slash"])
                continue

            elif item["type"] == "barLine":
                form_val = item["form"]
                if form_val == "||":
                    form_val = "dbl"
                bar_el = etree.SubElement(container_stack[-1], "barLine", form=form_val)
                bar_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                continue

            elif item["type"] == "break":
                next_note = None
                for k in range(idx + 1, len(resolved_music)):
                    if resolved_music[k]["type"] == "note":
                        next_note = resolved_music[k]
                        break
                if next_note:
                    custos_el = etree.SubElement(
                        container_stack[-1],
                        "custos",
                        pname=next_note["pname"],
                        oct=str(next_note["oct"]),
                    )
                    custos_el.set(
                        etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                        self.get_short_id(),
                    )

                # SB element follows custos inside the same measure (child of current_measure)
                sb_el = etree.SubElement(section, "sb")
                sb_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )

                # Open new measure for next system line
                measure_count += 1
                current_measure = etree.SubElement(
                    section, "measure", n=str(measure_count), right="invis"
                )
                current_measure.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )

                staff = etree.SubElement(current_measure, "staff", n="1")
                staff.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                layer = etree.SubElement(staff, "layer", n="1")
                layer.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )

                container_stack = [layer]
                continue

            elif item["type"] == "ligature_start":
                lig_el = etree.SubElement(container_stack[-1], "ligature")
                lig_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                container_stack.append(lig_el)
                continue
            elif item["type"] == "ligature_end":
                if container_stack[-1].tag == "ligature":
                    container_stack.pop()
                continue
            elif item["type"] == "beam_start":
                beam_el = etree.SubElement(container_stack[-1], "beam")
                beam_el.set(
                    etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                    self.get_short_id(),
                )
                container_stack.append(beam_el)
                active_beam = True
                is_first_note_of_beam = True
                continue
            elif item["type"] == "beam_end":
                if container_stack[-1].tag == "beam":
                    container_stack.pop()
                active_beam = False
                is_first_note_of_beam = False
                continue

            elif item["type"] in ["note", "rest", "space"]:
                # Standardize duration attributes into mensural ones for Verovio
                raw_dur = str(item["dur"])
                mensural_dur = self.dur_map.get(raw_dur, "semiminima")

                if item["type"] == "note":
                    if item["start_beam"]:
                        beam_el = etree.SubElement(container_stack[-1], "beam")
                        beam_el.set(
                            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                            self.get_short_id(),
                        )
                        container_stack.append(beam_el)
                        active_beam = True
                        is_first_note_of_beam = True

                    if item["start_ligature"]:
                        lig_el = etree.SubElement(container_stack[-1], "ligature")
                        lig_el.set(
                            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                            self.get_short_id(),
                        )
                        container_stack.append(lig_el)

                    note_id = self.get_short_id()
                    note_el = etree.SubElement(container_stack[-1], "note")
                    note_el.set(
                        etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                        note_id,
                    )
                    note_el.set("pname", item["pname"])
                    note_el.set("oct", str(item["oct"]))
                    note_el.set("dur", mensural_dur)

                    if item["dots"] > 0:
                        note_el.set("dots", str(item["dots"]))
                    if item["coloration"]:
                        note_el.set("coloration", "true")

                    # Avoid explicit stem.dir attribute on brevis and longa (causes Verovio thick stem issues)
                    if item["stem_dir"] and mensural_dur not in ["longa", "brevis"]:
                        note_el.set("stem.dir", item["stem_dir"])

                    # Key signature accidental suppression / correction logic
                    accid_to_write = item["accid"]
                    implied_accid = self.key_sig_accidentals.get(
                        active_key_sig, {}
                    ).get(item["pname"])

                    if implied_accid:
                        if accid_to_write == implied_accid:
                            if not item["force_accid"]:
                                accid_to_write = None
                        else:
                            if accid_to_write is None:
                                accid_to_write = "n"  # Explicit natural sign deviation

                    if accid_to_write:
                        if item["ficta"]:
                            acc_el = etree.SubElement(
                                note_el, "accid", accid=accid_to_write, func="edit"
                            )
                            acc_el.set(
                                etree.QName(
                                    "http://www.w3.org/XML/1998/namespace", "id"
                                ),
                                self.get_short_id(),
                            )
                        else:
                            note_el.set("accid", accid_to_write)

                    if item["start_slur"]:
                        slur_start_id = note_id
                    if item["end_slur"] and slur_start_id:
                        active_slurs.append((slur_start_id, note_id))
                        slur_start_id = None

                    # LYRIC ALIGNMENT with skips & beams
                    should_assign_lyric = True
                    if active_beam and not is_first_note_of_beam:
                        should_assign_lyric = False

                    if should_assign_lyric and lyric_idx < len(parsed_lyrics):
                        # Consume skips
                        while (
                            lyric_idx < len(parsed_lyrics)
                            and parsed_lyrics[lyric_idx]["type"] == "skip"
                        ):
                            lyric_idx += 1
                            should_assign_lyric = False
                            break

                    if should_assign_lyric and lyric_idx < len(parsed_lyrics):
                        lyr = parsed_lyrics[lyric_idx]
                        verse = etree.SubElement(note_el, "verse", n="1")
                        verse.set(
                            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                            self.get_short_id(),
                        )
                        syl = etree.SubElement(verse, "syl")
                        syl.set(
                            etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                            self.get_short_id(),
                        )
                        syl.text = lyr["text"]
                        if lyr["wordpos"] != "single":
                            syl.set("wordpos", lyr["wordpos"])
                        if lyr["con"]:
                            syl.set("con", lyr["con"])
                        lyric_idx += 1

                    if item["end_beam"]:
                        if container_stack[-1].tag == "beam":
                            container_stack.pop()
                        active_beam = False
                        is_first_note_of_beam = False
                    elif active_beam:
                        is_first_note_of_beam = False

                    if item["end_ligature"]:
                        if container_stack[-1].tag == "ligature":
                            container_stack.pop()

                elif item["type"] == "rest":
                    rest_el = etree.SubElement(container_stack[-1], "rest")
                    rest_el.set(
                        etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                        self.get_short_id(),
                    )
                    rest_el.set("dur", mensural_dur)
                    if item["dots"] > 0:
                        rest_el.set("dots", str(item["dots"]))

                elif item["type"] == "space":
                    space_el = etree.SubElement(container_stack[-1], "space")
                    space_el.set(
                        etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                        self.get_short_id(),
                    )
                    space_el.set("dur", mensural_dur)
                    if item["dots"] > 0:
                        space_el.set("dots", str(item["dots"]))

        for s_start, s_end in active_slurs:
            slur_el = etree.SubElement(
                section, "slur", start=f"#{s_start}", end=f"#{s_end}"
            )
            slur_el.set(
                etree.QName("http://www.w3.org/XML/1998/namespace", "id"),
                self.get_short_id(),
            )

        return etree.tostring(
            root, pretty_print=True, xml_declaration=True, encoding="UTF-8"
        )


def parse_metadata_file(filepath):
    metadata = {}
    if not filepath.exists():
        return metadata
    try:
        content = filepath.read_text(encoding="utf-8")
        patterns = {
            "title": r'title\s*=\s*"(.*?)"',
            "madrigal_book": r'madrigal_book\s*=\\s*"(.*?)"',
            "year": r'year\s*=\\s*"(.*?)"',
            "composer": r'composer\s*=\\s*"(.*?)"',
            "publisher": r'publisher\s*=\\s*"(.*?)"',
            "poet": r'poet\s*=\\s*"(.*?)"',
            "collection": r'collection\s*=\\s*"(.*?)"',
            "annotator": r'annotator\s*=\\s*"(.*?)"',
            "incipit": r'incipit\s*=\s*"(.*?)"',
        }
        for key, pattern in patterns.items():
            m = re.search(pattern, content)
            if m:
                metadata[key] = m.group(1)
    except Exception as e:
        print(f"Error parsing metadata file {filepath}: {e}")
    return metadata


def run_batch_compilation(root_dir, version_code):
    VOICE_MAP = {
        "c": "Cantus",
        "a": "Altus",
        "t": "Tenor",
        "b": "Bassus",
        "q": "Quintus",
        "sx": "Sextus",
        "st": "Septimus",
        "o": "Octavus",
    }

    path = Path(root_dir)
    print(f"Scanning for pieces in: {path.resolve()}")

    for piece_dir in sorted(path.iterdir()):
        if not piece_dir.is_dir():
            continue

        metadata_file = piece_dir / "metadata.ly"
        metadata = parse_metadata_file(metadata_file)

        print(f"\nProcessing piece directory: {piece_dir.name}")
        if metadata:
            print(f"Parsed metadata: {metadata}")

        converter = LilyPondToMEIConverter()

        for voice_code, vocal_label in VOICE_MAP.items():
            # Single search loop mapping f"{voice_code}_music_{version_code}.ly" as instructed
            note_file = piece_dir / f"{voice_code}_music_{version_code}.ly"

            if note_file.exists():
                print(f"  Found voice: {vocal_label} ({voice_code})")
                lyrics_file = piece_dir / f"{voice_code}_lyrics_{version_code}.ly"

                try:
                    notes_content = note_file.read_text(encoding="utf-8")
                    lyrics_content = (
                        lyrics_file.read_text(encoding="utf-8")
                        if lyrics_file.exists()
                        else ""
                    )

                    notes_content = converter.preprocess_notes(notes_content)
                    tokens = notes_content.split()
                    resolved_music = converter.resolve_relative_octaves(tokens)
                    parsed_lyrics = converter.parse_lyrics(lyrics_content)

                    v_metadata = metadata.copy()
                    v_metadata["vocal_label"] = vocal_label

                    title_str = v_metadata.get("title", "Converted LilyPond Score")
                    mei_xml = converter.generate_mei(
                        resolved_music,
                        parsed_lyrics,
                        title_text=title_str,
                        metadata=v_metadata,
                    )

                    output_file = piece_dir / f"{voice_code}_{version_code}.mei"
                    output_file.write_bytes(mei_xml)
                    print(f"    Generated partbook: {output_file.name}")

                except Exception as e:
                    print(
                        f"    Error processing voice {voice_code} in {piece_dir.name}: {e}"
                    )


def main():
    parser = argparse.ArgumentParser(
        description="Convert LilyPond strings or directory structures to MEI 5.1 XML."
    )
    parser.add_argument(
        "--notes", type=str, help="LilyPond musical tokens (space-separated)"
    )
    parser.add_argument(
        "--lyrics", type=str, default="", help="Space-separated lyrics tokens"
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Converted LilyPond Score",
        help="Title for the MEI header",
    )
    parser.add_argument(
        "--output", type=str, default="output.mei", help="Output file path"
    )

    # Batch options
    parser.add_argument(
        "--batch", action="store_true", help="Run in batch mode across directories"
    )
    parser.add_argument(
        "--dir", type=str, default=".", help="Root directory for batch scanning"
    )
    parser.add_argument(
        "--ver",
        type=str,
        default="d",
        help="Version code ('d' for diplomatic, 'p' for performance)",
    )
    args = parser.parse_args()

    if args.batch:
        run_batch_compilation(args.dir, args.ver)
        print("\nPartbook compilation completed.")
    else:
        if not args.notes:
            parser.error("--notes is required unless running in --batch mode.")
        converter = LilyPondToMEIConverter()
        resolved_music = converter.resolve_relative_octaves(args.notes)
        parsed_lyrics = converter.parse_lyrics(args.lyrics)
        mei_xml = converter.generate_mei(
            resolved_music, parsed_lyrics, title_text=args.title
        )

        with open(args.output, "wb") as f:
            f.write(mei_xml)
        print(f"MEI file generated successfully: {args.output}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        main()
    else:
        # Quick demonstration of all features
        print("Executing Unified Converter Test Suite:")
        conv = LilyPondToMEIConverter()
        snippet = '\\\\relative c\' { \\\\clef "petrucci-c3" \\\\key f \\\\major \\\\time 4/4 bf2 b!2 bf2 bf!2 \\\\break g\\\\longa \\\\bar "||" }'
        lyrics = "\\\\lyricmode { Oc -- chi lu -- cen -- ti }"
        print(f"Input Notes:  {snippet}")
        print(f"Input Lyrics: {lyrics}\n")

        music = conv.resolve_relative_octaves(snippet)
        lyr = conv.parse_lyrics(lyrics)
        xml = conv.generate_mei(music, lyr)
        print(xml.decode("utf-8"))
