% Generated by mei2ly.py from b_001.mei (Aruspix OMR draft, check against the images)
\relative c' {
  g'\longa \clef "petrucci-f3" \time 4/4 a,1 f2 g a1 r2 f f4 e d c b1 a2 r4 a \break
  g''\breve a2 e g d d4 a'2 f4 b c d2 a r4 d d c b a \break
  g\longa a2 g f1 r2 g g4 f e d c1 b r\breve d'2. c4 b2 f g d a'4 a d,2 g1 f r \break
  \time 4/4 a2 d, d e df! b' b b a1. b2 g1 b, r2 r4 d g f2 e4 e d2 d \break  % CHECK: accid f at f4 applied to d4: check
  g\longa a2 r4 a b2 e, r\longa c'2. d4 a2 d,1 r\breve r2 r4 d a'2 a b2. c4 b1 a r2 b g a \break
  g\longa a,2 f f4 e d c b1 a2 r4 a d2 f c c4 g'2 e4 a2. b4 c2 g1 \break
  g'\longa a2 r d, e g f1 b\longa d, d \break
}
