% Generated by mei2ly.py from c_001.mei (Aruspix OMR draft, check against the images)
\relative c' {
  \time 2/2 \clef "petrucci-c4" \clef "petrucci-g2" \time 4/4 af'!1 c2 b a1 r2 a a a b b e, a r4 a \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid before the first note of the system: may be a key signature read as an accidental; accid f at c4 applied to a4: check
  \clef "petrucci-c1" \clef "petrucci-c3" \time 2/2 bf,! b2 a d4 c2 c4 d e d2 c r d d2. e4.. \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid before the first note of the system: may be a key signature read as an accidental; accid f at d4 applied to b3: check
  cf'!2 c a f d' e e b2. a4 g8 a b g a2. b2 c b a g4 a2 r1 c2. b4 \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid f at a4 applied to c5: check
  gf!2 a f1. e2 f1 g2 a2. g4 f2. e8 d e2 f a a a b1. a2 a1 \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; dot without a preceding note/rest ignored; dot without a preceding note/rest ignored; dot at a4 far from f4
  af!2. a2 b c d e c c r1 r2 r4 a a g c2 a4 d4. c4 b8 a b2 a g4 a2. \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental
  bf!4 b c f, a2 b4 d c1 b2 r4 b d c c b a1 g r2 f a g f \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid before the first note of the system: may be a key signature read as an accidental
  ff! f f g g c, f r4 f2 f4 f2 e a4 g2 g4 a2. b4 c2 b2. b4 c2 c \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid f at a4 applied to f4: check
  df!4 c8 b a4 b c4. b8 g2 a\longa c \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; accid f at e4 applied to d5: check
}
