% Generated by mei2ly.py from t_001.mei (Aruspix OMR draft, check against the images)
\relative c' {
  \clef "petrucci-c4" \time 4/4 a1 d2 b a a a2. g4 f e d f2 e4 d8 e2 f \break  % CHECK: dot without a preceding note/rest ignored
  d''\breve \clef "petrucci-c2" r4 e, f2 e e g4 f2 g4 g f g2 f4 f b4. a4 g2 f4 \break
  \clef "petrucci-c3" c b2 r4 a c2 b a4 a c2 a a b4. c8 d4 b e2. d4 c4. b8 a b4 c g2 c \break  % CHECK: dot at g3 far from b3
  cf! b a e' d c1 a2 b1 a2 a r a4. g4 a2 g4 g d' d c b8 a b2 \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; dot without a preceding note/rest ignored; accid before the first note of the system: may be a key signature read as an accidental; accid f at e4 applied to c4: check; mensur {'num': '3', '{http://www.w3.org/XML/1998/namespace}id': 'm-ecc4a056-1ef1-4938-bcda-c5e247f5d718', 'ulx': '533'} not recognised, skipped; dot at e3 far from a3
  c2. g'8 g2 ef!1. e2 f1 e2. e4 f e d d c2 c4 g a g a b c2 g4 r2 g \break  % CHECK: dot at a4 far from c4
  ef'! f c4 d8 c d e f4 e d2 c g' e4 f2 e4 d2 c2. g'4 g2 g c,2. d4 \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental
  r2 cf! f d c4 c c b a g f a2 g8 f g2 a r4 c d2 c c e4 d2 e4 \break  % CHECK: accid before the first note of the system: may be a key signature read as an accidental; dot without a preceding note/rest ignored; accid f at a3 applied to c4: check
  e2 f e4 c2 b8 a b2 c1 r2 r4 a c b e2 e\breve \break
}
